name: Hello-spa CI/CD pipeline

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:

  build:
  
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node 15.x
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Install depedencies
      run: npm install
    - name: Install Angular CLI 9.1.0
      run: npm install -g @angular/cli@9.1.0
    - name: Install Chromium for unit tests
      run: apt install chromium; export CHROME_BIN='/usr/bin/chromium-browser'
    - name: Lint
      run: ng lint
    - name: Unit
      run: ng test --watch=false
    - name: build app
      run: ng build --output-path=dist --prod

#  deploy:
#
#    runs-on: ubuntu-20.04
#    needs: build
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v2
#    - name: Download build app
#      uses: actions/download-artifact@v2
#    - name: Deploy

