name: Docker Image CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Build the Docker image
      run: docker build --tag spa:$(date +%s) .
