name: Docker Image CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/pu5zkin/spa/spa:latest
    - name: Login to Docker registry
      run: echo ${{ secrets.TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - name: Push the Docker image to registry
      run: docker push ghcr.io/pu5zkin/spa/spa:latest

