name: Docker Image CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - run: npm install
      - run: ng lint
  
  unit:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Install chromium for test
        run: apk add chromium && export CHROME_BIN='/usr/bin/chromium-browser'
      - run: npm install
      - run: ng test --watch=false

  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/pu5zkin/spa/spa:latest
    - name: Login to Docker registry
      run: docker login ghcr.io -u $GITHUB_ACTOR -p ${{ secrets.TOKEN }}
    - name: Push the Docker image to registry
      run: docker push ghcr.io/pu5zkin/spa/spa:latest

