name: Hello-spa CI/CD pipeline

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:

  build:
  
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node 15.x
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Install depedencies
      run: npm install
    - name: install Angular CLI 9.1.0
      run: npm install -g @angular/cli@9.1.0
    - name: Lint
      run: ng lint
    - name: build
      run: ng build --output-path=dist --prod

